PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/RetiroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class RetiroController : Controller
    {
        // GET: Retiro
        public ActionResult Form()
        {
            ML.Contadores contador = new ML.Contadores();

            return View(contador);
        }
        [HttpPost]
        public ActionResult Form(int Retiro) {
            int saldoActual  = (int)Convert.ToInt64(Session["SaldoActual"]);
            if(saldoActual >= Retiro)
            {
                int saldoCajero = BL.SaldoCajero.GetSaldoCajero();
                if(saldoCajero >= Retiro)
                {
                    int CuentaSesion = (int)Convert.ToInt64(Session["NoCuentaRegistrada"]);
                    int descuentoSaldo = saldoActual - Retiro;
                    ML.Contadores result = BL.SaldoCajero.Retiro(Retiro);
                    bool resulltActualizacioSaldo = BL.CuentaSaldo.UpdateSaldoCliente(CuentaSesion,descuentoSaldo);

                    
                    return PartialView("ModalRetiro", result);
                }
                else
                {
                    ViewBag.Mensaje = "Saldo insuficiente para el retiro";
                    return PartialView("Modal");

                } 
                
            }
            else
            {
                ViewBag.Mensaje = "Saldo insuficiente para el retiro";
                return PartialView("Modal");
            }
        }
        public ActionResult Retorno()
        {
            return RedirectToAction("GetAll", "SaldoCuenta");
        }
    }
}

PL/Controllers/SaldoCuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class SaldoCuentaController : Controller
    {
        // GET: SaldoCuenta
        public ActionResult GetAll()
        {
            ML.CuentaSaldo cuentaSaldo = new ML.CuentaSaldo();

            int NoCuentaSesion = (int)Convert.ToInt64(Session["NoCuentaRegistrada"]);
            object result = BL.CuentaSaldo.GetSaldo(NoCuentaSesion);
            if(result != null)
            {
                cuentaSaldo = (ML.CuentaSaldo)result;
                Session["SaldoActual"] = cuentaSaldo.SaldoActual;
                return View(cuentaSaldo);
            }
            else
            {
                return View();
            } 
        }
    }
}

PL/Controllers/TransferirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class TransferirController : Controller
    {
        // GET: Transferir
        [HttpGet]
        public ActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Form(int monto, int cuentaReceptora)
        {
            ML.Tranferencia tranferencia = new ML.Tranferencia();
            ML.CuentaSaldo cuentaSaldo = new ML.CuentaSaldo();
            int NoCuentaSesion = (int)Convert.ToInt64(Session["NoCuentaRegistrada"]);
            int saldoActual = (int)Convert.ToInt64(Session["SaldoActual"]);
            if(saldoActual >= monto)
            {
                object resultGet = BL.Transferencia.GetCuentaReceptora(cuentaReceptora);
                if(resultGet != null)
                {
                    cuentaSaldo = (ML.CuentaSaldo)resultGet;
                    tranferencia.CuentaEmisora = NoCuentaSesion;
                    tranferencia.CuentaReceptora = cuentaReceptora;
                    tranferencia.saldoReceptor = cuentaSaldo.SaldoActual + monto;
                    tranferencia.SaldoEmnisor = saldoActual - monto;
                    bool Correct = BL.Transferencia.ActulizacionSaldos(tranferencia);
                    if (Correct)
                    {
                        ViewBag.Mensaje = "Operacion Exitosa!!!";
                    }
                    else
                    {
                        ViewBag.Mensaje = "Error al realzar la operacion, vuelava intentar";
                    }
                }
                else
                {
                    ViewBag.Mensaje = "No se encontro Numero de cuenta";
                }
            }
            else
            {
                ViewBag.Mensaje = "Saldo insuficiente para el retiro";
            }
            return PartialView("Modal");
        }
        public ActionResult Regreso()
        {
            return RedirectToAction("GetAll", "SaldoCuenta");
        }
    }
}

PL/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(ML.Usuario usuario) {
            int NoCuenta  = usuario.NoCuenta;
            int Nip = usuario.Nip;

            object result = BL.Usuario.GetCuenta(NoCuenta);


            if (result != null)
            {
                usuario = (ML.Usuario)result;
                if (usuario.Nip == Nip)
                {
                    Session["NoCuentaRegistrada"] = usuario.NoCuenta;
                    return RedirectToAction("GetAll", "SaldoCuenta");
                }
                else
                {
                    ViewBag.valido = true;
                    ViewBag.Mensaje = "Error Nip incorrecto";
                }
            }
            else
            {
                ViewBag.Mensaje = "Error cuenta incorrecta";
                ViewBag.valido = true;
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Retiro/Form.cshtml
@model ML.Contadores
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .formulario {
        width: 300px;
        padding: 16px;
        background-color: #f1f1f1;
        margin: 0 auto;
        box-shadow: 0 0 20px 0 rgba(0,0,0,0.2), 0 5px 5px 0 rgba(0,0,0,0.24);
    }

        .formulario input[type=text] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            border: none;
            background: #f1f1f1;
        }

        .formulario button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

            .formulario button:hover {
                opacity: 1;
            }
</style>

<h2>Ingreso de saldo</h2>
<body>

    <div class="formulario">
        <form action="/Retiro/Form" method="post">
            <label for="Retiro"><b>Cantidad a retirar</b></label>
            <input type="text" placeholder="Ingresa la cantidad" name="Retiro" required>
            <button type="submit" class="btn btn-primary">Retirar</button>
        </form>
    </div>

</body>

PL/Views/Retiro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "Form", "Retiro", htmlAttributes: new { @class = "btn btn-danger" })

                @*@if (ViewBag.valido)
                {
                    @Html.ActionLink("Vale", "Login", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
                }
                else
                {
                    @Html.ActionLink("Vale", "GetAll", "SaldoCuenta", htmlAttributes: new { @class = "btn btn-danger" })
                }*@

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Retiro/ModalRetiro.cshtml
@model ML.Contadores
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                 <table class="table table-hover">
     <thead>
         <tr>
             <th scope="col">Denominacion</th>
             <th scope="col">Cantidad de Billetes</th>
         </tr>
     </thead>
     <tbody>
         <tr>
             <th scope="row">$20</th>
             <td colspan="2">@Model.ContadorVenite</td>
         </tr>
         <tr>
             <th scope="row">$50</th>
             <td colspan="2">@Model.ContadorCincuenta</td>
         </tr>
         <tr>
             <th scope="row">$100</th>
             <td colspan="2">@Model.ContadorCien</td>
         </tr>
         <tr>
             <th scope="row">$200</th>
             <td colspan="2">@Model.ContadorDocientos</td>
         </tr>
         <tr>
             <th scope="row">$500</th>
             <td colspan="2">@Model.ContadorQuinientos</td>
         </tr>
         <tr>
             <th scope="row">$1000</th>
             <td colspan="2">@Model.ContadorMil</td>
         </tr>
     </tbody>
 </table>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "Retorno", "Retiro", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/SaldoCuenta/GetAll.cshtml
@model ML.CuentaSaldo
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body {
        font-family: Arial, sans-serif;
    }

    .balance-container {
        width: 300px;
        border: 1px solid #000;
        padding: 20px;
        margin: 0 auto;
        text-align: center;
    }

        .balance-container h2 {
            margin: 0 0 10px;
        }

        .balance-container p {
            font-size: 24px;
            font-weight: bold;
        }
    .boton {
        font-size: 20px;
        padding: 10px 24px;
        cursor: pointer;
        color: white;
        background-color: #4CAF50;
        border: none;
        border-radius: 5px;
        text-align: center;
        transition: 0.3s;
    }

    .boton:hover {
        background-color: #45a049;
    }
    #botones {
        margin-top: 50px;
        margin-left: 405px;
    }
    a {
        text-decoration: none;
    }

</style>
<div class="text-lg-start">
    <h2>Bienvenido</h2>
    <h5>@Model.Cuenta.Nombre</h5>
</div>
<hr />
<body>
    <div class="balance-container">
        <h2>Saldo Actual</h2>
        <p>$@Model.SaldoActual</p>
    </div>

    <div id="botones">
        <a class="boton" href="@Url.Action("Form", "Transferir")">
            <i class="fas fa-exchange-alt"></i>
            Tranferir
        </a>

        <a class="boton" href="@Url.Action("Form", "Retiro")">
            <i class="fas fa-money-bill-wave"></i>
            Retiro
        </a>
    </div>
    

</body>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Banco", "GetAll", "SaldoCuenta", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "GetAll", "SaldoCuenta", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="text-lg-end  flex-fill">
                        <a class="text-white  nav-link" href="@Url.Action("Login", "Usuario")"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
                    </li>
                </ul>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PL/Views/Usuario/Login.cshtml
@model ML.Usuario
@{
    Layout = null;
}

<!doctype html>
<html>
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <meta charset="utf-8" />
    <title>Login</title>
    <style type="text/css">
        body {
            margin: 0;
            color: #6a6f8c;
            background: #c8c8c8;
            font: 600 16px/18px "Open Sans", sans-serif;
        }

        *,
        :after,
        :before {
            box-sizing: border-box;
        }

        .clearfix:after,
        .clearfix:before {
            content: "";
            display: table;
        }

        .clearfix:after {
            clear: both;
            display: block;
        }

        a {
            color: inherit;
            text-decoration: none;
        }

        .login-wrap {
            width: 100%;
            margin: auto;
            margin-top: 25px;
            max-width: 525px;
            min-height: 670px;
            position: relative;
            background: url(https://raw.githubusercontent.com/khadkamhn/day-01-login-form/master/img/bg.jpg) no-repeat center;
            box-shadow: 0 12px 15px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
        }

        .login-html {
            width: 100%;
            height: 100%;
            position: absolute;
            padding: 90px 70px 50px 70px;
            background: rgba(40, 57, 101, 0.9);
        }

            .login-html .sign-in-htm,
            .login-html .sign-up-htm {
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                position: absolute;
                transform: rotateY(180deg);
                backface-visibility: hidden;
                transition: all 0.4s linear;
            }

            .login-html .sign-in,
            .login-html .sign-up,
            .login-form .group .check {
                display: none;
            }

            .login-html .tab,
            .login-form .group .label,
            .login-form .group .button {
                text-transform: uppercase;
            }

            .login-html .tab {
                font-size: 22px;
                margin-right: 15px;
                padding-bottom: 5px;
                margin: 0 15px 10px 0;
                display: inline-block;
                border-bottom: 2px solid transparent;
            }

            .login-html .sign-in:checked + .tab,
            .login-html .sign-up:checked + .tab {
                color: #fff;
                border-color: #1161ee;
            }

        .login-form {
            min-height: 345px;
            position: relative;
            perspective: 1000px;
            transform-style: preserve-3d;
        }

            .login-form .group {
                margin-bottom: 15px;
            }

                .login-form .group .label,
                .login-form .group .input,
                .login-form .group .button {
                    width: 100%;
                    color: #fff;
                    display: block;
                }

                .login-form .group .input,
                .login-form .group .button {
                    border: none;
                    padding: 15px 20px;
                    border-radius: 25px;
                    background: rgba(255, 255, 255, 0.1);
                }

                .login-form .group input[data-type="password"] {
                    text-security: circle;
                    -webkit-text-security: circle;
                }

                .login-form .group .label {
                    color: #aaa;
                    font-size: 12px;
                }

                .login-form .group .button {
                    background: #1161ee;
                }

                .login-form .group label .icon {
                    width: 15px;
                    height: 15px;
                    border-radius: 2px;
                    position: relative;
                    display: inline-block;
                    background: rgba(255, 255, 255, 0.1);
                }

                    .login-form .group label .icon:before,
                    .login-form .group label .icon:after {
                        content: "";
                        width: 10px;
                        height: 2px;
                        background: #fff;
                        position: absolute;
                        transition: all 0.2s ease-in-out 0s;
                    }

                    .login-form .group label .icon:before {
                        left: 3px;
                        width: 5px;
                        bottom: 6px;
                        transform: scale(0) rotate(0);
                    }

                    .login-form .group label .icon:after {
                        top: 6px;
                        right: 0;
                        transform: scale(0) rotate(0);
                    }

                .login-form .group .check:checked + label {
                    color: #fff;
                }

                    .login-form .group .check:checked + label .icon {
                        background: #1161ee;
                    }

                        .login-form .group .check:checked + label .icon:before {
                            transform: scale(1) rotate(45deg);
                        }

                        .login-form .group .check:checked + label .icon:after {
                            transform: scale(1) rotate(-45deg);
                        }

        .login-html
        .sign-in:checked + .tab + .sign-up + .tab + .login-form
        .sign-in-htm {
            transform: rotate(0);
        }

        .login-html .sign-up:checked + .tab + .login-form .sign-up-htm {
            transform: rotate(0);
        }

        .hr {
            height: 2px;
            margin: 60px 0 50px 0;
            background: rgba(255, 255, 255, 0.2);
        }

        .foot-lnk {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
            @* FormularioLogin *@

            <div class="login-form">
                @using (Html.BeginForm("Login", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="sign-in-htm">
                        <div class="group">
                            <label for="user" class="label">No. Cuenta</label>
                            @Html.TextBoxFor(model => Model.NoCuenta, new { @class = "input", @type = "text", @id = "user" })
                        </div>
                        <div class="group">
                            <label for="user" class="label">Nip</label>
                            @Html.TextBoxFor(model => Model.Nip, new { @class = "input", @type = "password", @id = "pass" })
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <a href="@Url.Action("Recuperar", "Usuario")">Forgot Password?</a>
                        </div>
                    </div>
                }

                @* Fin del formulario Login *@
                @* inicio del formulario de registyrar *@
                
            </div>
        </div>
    </div>
</body>
</html>

PL/Views/Usuario/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@

                @if (ViewBag.valido)
                {
                    @Html.ActionLink("Vale", "Login", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
                }
                else
                {
                    @Html.ActionLink("Vale", "GetAll", "SaldoCuenta", htmlAttributes: new { @class = "btn btn-danger" })
                }

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>